server:
  port: 8082
  servlet:
    context-path: /api/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update

microservice:
  recomendation:
    url: http://localhost:8081
---

server:
  port: 8082
  servlet:
    context-path: /api/

spring:
  config:
    activate:
      on-profile:
      - docker
  datasource:
    url: jdbc:postgresql://postgres:5432/warehouse
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update  
      
microservice:
  recomendation:
    url: http://poc-microservice-product:8081      